# The purpose of this workflow is to publish the bulwark workspace of crates
# whenever a bulwark release tag is created. This is a simplified version of
# the wasmtime release workflow.

name: "Publish to Crates.io"

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    if: github.repository == 'bulwark-security/bulwark'
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Install Rust
      uses: dtolnay/rust-toolchain@21dc36fb71dd22e3317045c0c31a3f4249868b17
      with:
        toolchain: stable
        components: clippy
        target: wasm32-wasi

    - name: Ensure generated files are available
      uses: clechasseur/rs-cargo@5cd564345ef5b1136392a1dc943b33a3a888b873 # v2.0.2
      with:
        command: test
        args: -p bulwark-config -p bulwark-sdk

    - name: Publish Crates
      run: |
        rustc scripts/publish.rs -o /tmp/publish
        /tmp/publish publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
